export const amenities = [
  { key: "pool", icon: "pool.svg", label: "Бассейн" },
  { key: "bar", icon: "bar.svg", label: "Бар" },
  { key: "gym", icon: "gym.svg", label: "Спортзал" },
  { key: "cafe", icon: "cafe.svg", label: "Кафе" },
  { key: "spa", icon: "spa.svg", label: "Спа" },
  { key: "mountainView", icon: "mountain_view.svg", label: "Вид на горы" },
  { key: "coffeeShop", icon: "coffee_shop.svg", label: "Кофейня" },
  { key: "sauna", icon: "sauna.svg", label: "Сауна" },
  { key: "restaurant", icon: "restaurant.svg", label: "Ресторан" },
  { key: "beachClub", icon: "beach_club.svg", label: "Пляжный клуб" },
  { key: "park", icon: "park.svg", label: "Парк" },
  { key: "seaView", icon: "sea_view.svg", label: "Вид на море" },
  { key: "businessCenter", icon: "business_center.svg", label: "Бизнес центр" },
  { key: "waterPark", icon: "water_park.svg", label: "Аквапарк" },
  { key: "carRental", icon: "car_rental.svg", label: "Аренда машин" },
  { key: "kidsRoom", icon: "kids_room.svg", label: "Детская комната" },
  {
    key: "outdoorPlayground",
    icon: "outdoor_playground.svg",
    label: "Открытая детская игровая площадка",
  },
  {
    key: "walkingPaths",
    icon: "walking_paths.svg",
    label: "Пешеходные дорожки и тропинки",
  },
  {
    key: "courts",
    icon: "courts.svg",
    label: "Баскетбольный и теннисный корты",
  },
  {
    key: "openAirCinema",
    icon: "open_air_cinema.svg",
    label: "Кинотеатр на открытом воздухе",
  },
  { key: "indoorPool", icon: "indoor_pool.svg", label: "Крытый бассейн" },
  {
    key: "botanicalGardens",
    icon: "botanical_gardens.svg",
    label: "Ботанический сады",
  },
  { key: "bikeRental", icon: "bike_rental.svg", label: "Аренда велосипедов" },
  { key: "bbqArea", icon: "bbq_area.svg", label: "Зона отдыха и барбекю" },
  {
    key: "meditationArea",
    icon: "meditation_area.svg",
    label: "Площадка для медитации",
  },
];
